# Generated by Django 6.0.7 on 2026-07-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('local', 'local'), ('google', 'google'), ('github', 'github')], default='local', max_length=20),
        ),
    ]
